remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for Ter Saaami ⇒ Russian
description: An electronic dictionary from Ter Saaami to Russian
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: default
