theme: jekyll-theme-giellalt
title: Dictionary for Ter Saaami ⇒ Russian
description: An electronic dictionary from Ter Saaami to Russian

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
